services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: release
        ports:
            - '4000:4000'
        environment:
            - APP_PORT=4000
            - DB_HOST=database
            - SMTP_HOST=mailhog

    database:
        image: postgres:16-alpine
        shm_size: 128mb
        environment:
            POSTGRES_DB: matcha
            POSTGRES_USER: matcha
            POSTGRES_PASSWORD: matcha
        volumes:
            - database:/var/lib/postgresql/data
            - ./data/initdb:/docker-entrypoint-initdb.d

    mailhog:
        image: mailhog/mailhog
        ports:
            - '8025:8025' # Web interface (for demo purposes)

volumes:
    database:
