version: '3.9'

services:
    dev-database:
        image: postgres:16-alpine
        shm_size: 128mb
        environment:
            POSTGRES_DB: matcha
            POSTGRES_USER: matcha
            POSTGRES_PASSWORD: matcha
        volumes:
            - dev-database:/var/lib/postgresql/data
            - ./data/initdb:/docker-entrypoint-initdb.d
        ports:
            - '5432:5432'
        command: [ "postgres", "-c", "log_statement=all", "-c", "log_destination=stderr" ]

    dev-mailhog:
        image: mailhog/mailhog
        ports:
            - '1025:1025'
            - '8025:8025'

volumes:
    dev-database:
