services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: release
        ports:
            - '4000:4000'
        environment:
            - APP_PORT=4000
            - APP_HOST=1A3.42angouleme.fr
            - DB_HOST=database
            - SMTP_HOST=mailhog
            - APP_IS_ASSESSMENT=true
        volumes:
            -   uploads:/app/uploads

    database:
        image: postgres:16-alpine
        shm_size: 128mb
        environment:
            POSTGRES_DB: matcha
            POSTGRES_USER: matcha
            POSTGRES_PASSWORD: matcha
        volumes:
            - database:/var/lib/postgresql/data
            - ./data/initdb:/docker-entrypoint-initdb.d
        ports:
            - '5432:5432' # to allow seeding the database for demo purposes (do not expose in production)

    mailhog:
        image: mailhog/mailhog
        ports:
            - '8025:8025' # Web interface (for demo purposes)

volumes:
    database:
    uploads:
